spring:
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

parcial:
  enable_flyweight: true
  max_pool_size: 2
  encrypt: com.zayver.parcial.bridge.encrypt.AESEncrypt
